# Generated by Django 2.0.3 on 2019-12-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='isCoffeeCategory',
            new_name='isDrinkCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=2499),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
