# Generated by Django 2.0.3 on 2019-12-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_auto_20191223_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(max_length=511),
        ),
    ]
