# Generated by Django 2.0.3 on 2019-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_auto_20191223_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isLightColor',
            field=models.BooleanField(default=True),
        ),
    ]
