# Generated by Django 2.0.3 on 2019-12-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_product_islightcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isLightColor',
            field=models.BooleanField(default=False),
        ),
    ]
