# Generated by Django 2.0.3 on 2019-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_auto_20191224_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
